# Generated by Django 6.0.3 on 2026-04-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=20, verbose_name='Stolga neshe adam siyiwi')),
                ('location', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
