# Generated by Django 6.0.3 on 2026-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Stolga neshe adam siyiwi'),
        ),
    ]
